apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: taskmanager-ingress
  namespace: "02220155"
  labels:
    app: taskmanager
    student: "02220155"
spec:
  ingressClassName: nginx
  rules:
    - host: 02220155.cstapp.site   # Replace with your actual domain
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: taskmanager-service
                port:
                  number: 80
